language: r
sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

env:
  - LINTR_COMMENT_BOT=false

addons:
  apt:
    packages:
      - libjpeg-dev
      - libxml2-dev
      - libz-dev
      - libmpfr-dev

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

script:
  - Rscript _build.R

after_success:
  - Rscript _lint_all.R

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _book
  fqdn: chicsof.tech
  on:
    branch: master
